config/routes.rb
GooglePlay::Application.routes.draw do
  resources :signin, :only => [:index] do
    collection do
      post :connect
      post :disconnect
      post :save_user
      get :refresh_connection
    end
  end

  resources :activities, :only => [:index, :show] do
    resources :comments, :only => [:index]
    collection do
      get :search
    end
  end

  resources :comments, :only => [:show]

  resources :calendars, :only => [:show, :create, :update, :destroy] do
    resources :calendar_events, :only => [:index, :new, :show, :create, :update, :destroy], :path => 'events', :as => 'events' do
      member do
        post :move
        get :destroy_show, path: 'destroy'
      end
      collection do
        post :quick_add
      end
    end
    member do
      post :clear
    end
  end

  resources :calendar_lists, :only => [:index, :show, :create, :update, :destroy]

  resources :circles do
    member do
      get :destroy_show, path: 'destroy'
      get :circle_files
      post :add_message
      post :add_wallpin
      delete :delete_item
      get :circle_peoples
      post :remove_team_member
    end
    collection do
      get :circles_names
      post :add_friend_to_team
    end
  end

  resources :colors, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :calendar, :as => 'calendar'
      get :event, :as => 'event'
    end
  end

  resources :files, :only => [:index, :show, :create, :update, :destroy] do
    resources :file_comments, :only => [:index, :show, :create, :update, :destroy], :path => 'comments', :as => 'comments' do
      resources :replies, :only => [:index, :show, :create, :update, :destroy]
      collection do
        get :comments_show, :path => "show", :as => "show"
      end
    end
    member do
      post :copy
      post :touch
      post :trash
      post :untrash
      get :destroy_show, path: 'destroy'
      get :copy_show, path: 'copy'
      get :share
    end
    collection do
      post :insert_new
      post :share_files
     
      get :search_files
    end
  end

  resources :peoples, :only => [:index, :show] do
    collection do
      get :search
      get :monea_email_search
      get :list_by_activity
      post :add_people
    end
  end

  resources :task_lists, :only => [:index, :show, :create, :update, :destroy] do
    resources :tasks, :only => [:index, :show, :new, :create, :update, :destroy] do
      member do
        put :complete_task
        get :destroy_show, path: 'destroy'
        get :complete_show, path: 'complete'
      end
      collection do
        post :clear
      end
    end
    member do
      get :destroy_show, path: 'destroy'
    end
    collection do
      post :create_task
    end
  end

  root 'signin#index'
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	before_action :discover_api
	before_action :get_task, only: [:show, :update, :complete_task, :destroy_show, :complete_show]

	def index
    	# Get the list of tasks in task list.
    	response = $client.execute(:api_method => @tasks.tasks.list,
								:parameters => {'tasklist' => params[:task_list_id]})

    	render json: response.data.to_json
	end

	def show
    	@task = @response.data
		@task_list_id = params[:task_list_id]
        respond_to do |format|
            format.html
            format.js
        end
	end

	def new
    	respond_to do |format|
      		format.js { @task_list_id = params[:task_list_id] }
    	end
  	end

	def create
    	task = {
    			title: "#{params[:task][:title]}" ,
    			notes: params[:task][:notes] ,
    			due: params[:task][:due].to_datetime
				}

    	# Create the task in task list.
    	result = $client.execute(:api_method => @tasks.tasks.insert,
    							:parameters => {'tasklist' => params[:task_list_id]},
    							:body_object => task,
								:headers => {'Content-Type' => 'application/json'})

    	# render json: response.data.to_json
        @task = result.data
        @task_list_id = params[:task_list_id]
        respond_to do |format|
            format.js
        end
	end

	def update
        if params[:task][:status] == "needsAction"
            $client.execute(:api_method => @tasks.tasks.delete,
                                :parameters => {'tasklist' => params[:task_list_id], 'task' => params[:id]})

            task = {
                title:  params[:task][:title],
                notes:  params[:task][:notes],
                due:  params[:task][:due].to_datetime
            }

            # Create the task in task list.
            result = $client.execute(:api_method => @tasks.tasks.insert,
                                    :parameters => {'tasklist' => params[:task_list_id]},
                                    :body_object => task,
                                    :headers => {'Content-Type' => 'application/json'})
        elsif params[:task][:status] == "completed"
            task = @response.data
        	task.title = params[:task][:title]
        	task.notes = params[:task][:notes] unless nil
        	task.due = params[:task][:due].to_datetime unless nil
        	task.status = params[:task][:status]

        	# Update the task in task list.
        	result = $client.execute(:api_method => @tasks.tasks.update,
        							:parameters => {'tasklist' => params[:task_list_id], 'task' => params[:id]},
        							:body_object => task,
    								:headers => {'Content-Type' => 'application/json'})
        end
        @div_id = params[:id]
        @task = result.data
        @task_list_id = params[:task_list_id]
        respond_to do |format|
            format.js
        end
    	# render json: result.data.to_json
    	#redirect_to root_path
	end

	def destroy
    	# Delete the task in task list.
    	response = $client.execute(:api_method => @tasks.tasks.delete,
    							:parameters => {'tasklist' => params[:task_list_id], 'task' => params[:id]})

    	# render json: response.data.to_json
        respond_to do |format|
            format.js { @result = response, @div_id = params[:id] }
        end
	end

	def destroy_show
		@task = @response.data
		@task_list_id = params[:task_list_id]
        respond_to do |format|
            format.html
            format.js
        end
    end

	def complete_task
		task = @response.data
		task.status = 'completed'
		# Update the task with status as complete
		result = $client.execute(:api_method => @tasks.tasks.update,
		                        :parameters => {'tasklist' => params[:task_list_id], 'task' => params[:id]},
		                        :body_object => task,
		                        :headers => {'Content-Type' => 'application/json'})
        @task = result.data
        @task_list_id = params[:task_list_id]
		# render json: result.data.to_json
        respond_to do |format|
            format.js 
        end
		#redirect_to root_path
	end

	def complete_show
        @task = @response.data
		@task_list_id = params[:task_list_id]
        respond_to do |format|
            format.html
            format.js
        end
    end

	# Clears all completed tasks from the specified task list. The affected tasks will be marked as 'hidden' and no longer be returned by default when retrieving all tasks for a task list.
	def clear
		# Get the task with tasklist id and task id.
		response = $client.execute(:api_method => @tasks.tasks.clear,
		                          :parameters => {'tasklist' => params[:task_list_id]})

		render json: response.data.to_json
	end

	private

	def discover_api
		# Authorizing the client and constructing a Google+ service.
		@tasks = $client.discovered_api('tasks', 'v1')
	end

	def get_task
    	# Get the task in task list.
    	@response = $client.execute(:api_method => @tasks.tasks.get,
    							:parameters => {'tasklist' => params[:task_list_id], 'task' => params[:id]})
	end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_task_complete.html.erb
<p>Congrats, you successfully completed your task.</p>
<br>
<p><%= task.title %></p>

app/views/tasks/_task_complete_show.html.erb
<div id="js-update-task-modal-body">
  <h3 class="pink-header">Are you sure?</h3>
  <%= form_tag(complete_task_task_list_task_path(task_list_id, task.id), :id => "complete_task", :method => "put", remote: true) do %>
    <%= submit_tag "Complete", class: "btn" %>
  <% end %>
</div>

app/views/tasks/_task_create.html.erb
<h3 class="pink-header">Create Task</h3>
<div id="js-task-create-result-body" class="modal-body">
  <%= form_tag(task_list_tasks_path(task_list_id), :id => "create_task", :method => "post", remote: true) do %>
    <div class="form-group">
      <%= hidden_field_tag "task_list_id", task_list_id %>
      Title: <%= text_field_tag "task[title]", "", class: "white-pink", placeholder: "Title" %>
      Notes: <%= text_field_tag "task[notes]", "", class: "white-pink", placeholder: "Notes" %>
      Due: <%= text_field_tag "task[due]", "#{DateTime.now.strftime('%d/%m/%Y %H:%M')}", class: "white-pink" %>
      <%= hidden_field_tag "task[circle_id]", "" %>
      <br>
      <%= submit_tag "Add", class: "btn" %>
    <% end %>
    </div>
</div>
<div id="js-task-create-result-footer">
</div>

app/views/tasks/_task_delete.html.erb
<div  id="js-task-delete-result-body">
  <h3 class="pink-header">Are you sure?</h3>
  <%= form_tag(task_list_task_path(task_list_id, task.id), :method => "delete", remote: true) do %>
  <%= submit_tag 'Yes', class: 'btn' %>
  <% end %>
</div>

app/views/tasks/_task_show.html.erb
    <h3 class="pink-header">Task Details</h3>
    <div id="js-update-task-modal-body">
      <%= form_tag(task_list_task_path(task_list_id, task.id), :id => "update_task", :method => "put", remote: true) do %>
        <div class="form-group">
          Title: <%= text_field_tag "task[title]", task.title, class: "white-pink", placeholder: "Title" %>
          Notes: <%= text_field_tag "task[notes]", task.notes, class: "white-pink", placeholder: "Notes" %>
          <% if task.status == "completed" %>
            Completed Date: <%= text_field_tag "task[due]", task.completed, class: "white-pink", placeholder: "Completed Date" %>
            Status: <%= select_tag "task[status]", options_for_select([ ["Complete","completed"], ["Not Complete","needsAction"] ], "completed"), class: "white-pink" %>
          <% else %>
            Due Date: <%= text_field_tag "task[due]", task.due, class: "white-pink", placeholder: "Due Date" %>
            Status: <%= select_tag "task[status]", options_for_select([ ["Complete","completed"], ["Not Complete","needsAction"] ], "needsAction"), class: "" %>
          <% end %>
          <%= hidden_field_tag "task[circle_id]", task.title[/.*\[([^\]]*)/,1] %>
        </div>
        <%= submit_tag "Update", class: 'btn' %>
      <% end %>
    </div>
    

app/views/tasks/_task_updated.html.erb
<p>You task was successfully updated.</p>
<br>
<p><%= task.title %></p>

app/views/tasks/complete_show.js.erb
$("#empty-modal-body-container").empty();
$("#empty-modal-body-container").html("<%= escape_javascript(render partial: 'task_complete_show', locals: { task: @task, task_list_id: @task_list_id }) %>");
$("#modal-window-empty").modal("show");

app/views/tasks/complete_task.js.erb
var html_id = '#' + '<%= @task.id %>'

$(html_id).hide();

task = {
	id: '<%= @task.id %>',
	title: '<%= @task.title %>',
	due: '<%= @task.due %>',
	completed: '<%= @task.completed %>',
	notes: '<%= @task.notes %>',
	status: '<%= @task.status %>'
}

var taskListId = '<%= @task_list_id %>'

$('#tasks-complete-container').prepend(
		uiHelper.tasksHtml(task, taskListId)
);

$("#js-update-task-modal-body").html("<%= escape_javascript(render partial: 'task_complete', locals: { task: @task }) %>");

Webflow.require("slider").redraw();

app/views/tasks/create.js.erb
$('#js-task-create-result-body').empty().fadeOut();

task = {
  id: '<%= @task.id %>',
  title: '<%= @task.title %>',
  due: '<%= @task.due %>',
  completed: '<%= @task.completed %>',
  notes: '<%= @task.notes %>',
  status: '<%= @task.status %>'
}
var html = '<p>' + ' Task added successfully ' + task.title + 
			     '</p>' 

$('#js-task-create-result-footer').show();
$('#js-task-create-result-body').append(html).fadeIn();

var taskListId = '<%= @task_list_id %>'

$('#tasks-pending-container').prepend(
     uiHelper.tasksHtml(task, taskListId)
);

Webflow.require("slider").redraw();

app/views/tasks/destroy.js.erb
$('#js-task-delete-result-body').empty();
var id = '#' + '<%= @div_id %>'
$(id).hide();
var html = '<p>' + 'Successfully deleted boss: ' + '<i class="fa fa-bomb"><i>' +  '</p>'
$('#js-task-delete-result-body').append(html);

app/views/tasks/destroy_show.js.erb
$("#empty-modal-body-container").empty();
$("#empty-modal-body-container").html("<%= escape_javascript(render partial: 'task_delete', locals: { task: @task, task_list_id: @task_list_id }) %>");
$("#modal-window-empty").modal("show");

app/views/tasks/new.js.erb
$("#empty-modal-body-container").empty();
$("#empty-modal-body-container").html("<%= escape_javascript(render partial: 'task_create', locals: { task_list_id: @task_list_id }) %>");
$("#modal-window-empty").modal("show");

app/views/tasks/show.js.erb
$("#empty-modal-body-container").empty();
$("#empty-modal-body-container").html("<%= escape_javascript(render partial: 'task_show', locals: { task: @task, task_list_id: @task_list_id }) %>");
$("#modal-window-empty").modal("show");

app/views/tasks/update.js.erb
var div_id = '#'+'<%= @div_id %>'

$(div_id).hide();

task = {
	id: '<%= @task.id %>',
	title: '<%= @task.title %>',
	due: '<%= @task.due %>',
	completed: '<%= @task.completed %>',
	notes: '<%= @task.notes %>',
	status: '<%= @task.status %>'
}

var taskListId = '<%= @task_list_id %>'

$("#js-update-task-modal-body").html("<%= escape_javascript(render partial: 'task_updated', locals: { task: @task }) %>");

if ( task.status == "completed" ) {
	console.log('completed')
	$('#tasks-complete-container').append(
		uiHelper.tasksHtml(task, taskListId)
	);

} else {
	console.log('NOT completed')
	$('#tasks-pending-container').append(
         uiHelper.tasksHtml(task, taskListId)
    );

};

Webflow.require("slider").redraw();