config/routes.rb
GooglePlay::Application.routes.draw do
  resources :signin, :only => [:index] do
    collection do
      post :connect
      post :disconnect
      post :save_user
      get :refresh_connection
    end
  end

  resources :activities, :only => [:index, :show] do
    resources :comments, :only => [:index]
    collection do
      get :search
    end
  end

  resources :comments, :only => [:show]

  resources :calendars, :only => [:show, :create, :update, :destroy] do
    resources :calendar_events, :only => [:index, :new, :show, :create, :update, :destroy], :path => 'events', :as => 'events' do
      member do
        post :move
        get :destroy_show, path: 'destroy'
      end
      collection do
        post :quick_add
      end
    end
    member do
      post :clear
    end
  end

  resources :calendar_lists, :only => [:index, :show, :create, :update, :destroy]

  resources :circles do
    member do
      get :destroy_show, path: 'destroy'
      get :circle_files
      post :add_message
      post :add_wallpin
      delete :delete_item
      get :circle_peoples
      post :remove_team_member
    end
    collection do
      get :circles_names
      post :add_friend_to_team
    end
  end

  resources :colors, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :calendar, :as => 'calendar'
      get :event, :as => 'event'
    end
  end

  resources :files, :only => [:index, :show, :create, :update, :destroy] do
    resources :file_comments, :only => [:index, :show, :create, :update, :destroy], :path => 'comments', :as => 'comments' do
      resources :replies, :only => [:index, :show, :create, :update, :destroy]
      collection do
        get :comments_show, :path => "show", :as => "show"
      end
    end
    member do
      post :copy
      post :touch
      post :trash
      post :untrash
      get :destroy_show, path: 'destroy'
      get :copy_show, path: 'copy'
      get :share
    end
    collection do
      post :insert_new
      post :share_files
     
      get :search_files
    end
  end

  resources :peoples, :only => [:index, :show] do
    collection do
      get :search
      get :monea_email_search
      get :list_by_activity
      post :add_people
    end
  end

  resources :task_lists, :only => [:index, :show, :create, :update, :destroy] do
    resources :tasks, :only => [:index, :show, :new, :create, :update, :destroy] do
      member do
        put :complete_task
        get :destroy_show, path: 'destroy'
        get :complete_show, path: 'complete'
      end
      collection do
        post :clear
      end
    end
    member do
      get :destroy_show, path: 'destroy'
    end
    collection do
      post :create_task
    end
  end

  root 'signin#index'
end

app/controllers/files_controller.rb
class FilesController < ApplicationController

	before_action :discover_api, except: [:share_files]
	before_action :get_file, only: [:show, :update, :destroy_show, :copy_show]

	def index
    	# Get the list of files in drive
	    response = $client.execute(:api_method => @drive.files.list)
	    # respond_to do |f| 
	    # 	f.html
	    # 	f.json { render json: response.data.to_json }
	    # end
	    render json: response.data.to_json
	end

	def show
	    render json: @response.data.to_json
	end

	def create
		# http only and only import file user and team
		#need to clean up without impacting main file creates and teamFile.new
		#and blend in insert_new
		google = GoogleService.new($client, @drive)
		org_filename = params[:file].original_filename
		content_type = params[:file].content_type
		file_path = params[:file].tempfile.path
	  	
	  	file = @drive.files.insert.request_schema.new({
	    	'title' => org_filename,
    		'mimeType' => content_type
	  	})
	  	
	  	file.properties = [{"key" => "circle_id", "value" => params[:circle_id]}] unless params[:circle_id].blank?

	  	media = google.load_drive_media(file_path, content_type)

	  	response = google.execute_cloud_insert(media, file)

	  	if params[:circle_id].present?
		  	TeamFile.create(circle_id: params[:circle_id], file_id: response.data.id)
		  	@circle = Circle.find(params[:circle_id])
		  	team_members = @circle.team_members
		    if team_members.present?
		    	team_members.each do |team_member|
		    		user = User.find_by(google_id: team_member.google_id)
		    		if user
		    			google.insert_new_files_permission(user, response.data.id)
		    		end
		    	end
		    end
		    unless current_user.id == @circle.user_id
		    	@circle_owner = User.find(@circle.user_id)
		    	google.insert_new_files_permission(@circle_owner, response.data.id)
		    end
		    redirect_to circle_path(params[:circle_id])
		else
	    	redirect_to root_path
	    end
	end

	def insert_new
	  #JS only not import only SS or Doc
	  google = GoogleService.new($client, @drive)

	  file = @drive.files.insert.request_schema.new({
	    'title' => params[:title],
	    'mimeType' => params[:mimeType]
	  })
	  media = ""
	  if params[:mimeType] == 'application/vnd.google-apps.spreadsheet'
	  	media = google.load_drive_media("#{Rails.root}/app/files/monea-build.csv", 'text/csv')
	  else
	  	media = google.load_drive_media("#{Rails.root}/app/files/monea-build.txt", 'text/plain')
	  end

	  response = google.execute_cloud_insert(media, file)

	  if params[:circle_id].present?
		  	TeamFile.create(circle_id: params[:circle_id], file_id: response.data.id)
	  		@circle = Circle.find(params[:circle_id])
		  	team_members = @circle.team_members
		    if team_members.present?
		    	team_members.each do |team_member|
		    		user = User.find_by(google_id: team_member.google_id)
		    		if user
		    			google.insert_new_files_permission(user, response.data.id)
		    		end
		    	end
		    end
		    unless current_user.id == @circle.user_id
		    	@circle_owner = User.find(@circle.user_id)
		    	google.insert_new_files_permission(@circle_owner, response.data.id)
		    end
	  end
      respond_to do |format|
	      format.js { @file = response.data }
	   end
	end

	def update
	    file = @response.data

	    file.title = params[:title] if params[:title].present?
	    file.description = params[:description] if params[:description].present?
	    file.mime_type = params[:mime_type] if params[:mime_type].present?

	    media = Google::APIClient::UploadIO.new(params[:file].tempfile.path, params[:file].content_type)

	    result = $client.execute(
	      	:api_method => @drive.files.update,
	      	:body_object => file,
	      	:media => media,
	      	:parameters => { 'fileId' => file.id,
	                       'newRevision' => false,
	                       'uploadType' => 'multipart',
	                       'alt' => 'json' })

	    render json: result.data.to_json
	end

	def destroy
		# Delete the file from drive
	    response = $client.execute(:api_method => @drive.files.delete,
    							:parameters => { 'fileId' => params[:id] })

	    teams_file_belongs_to = TeamFile.all.where(file_id: params[:id])
	    teams_file_belongs_to.each do |t_file|
	    	t_file.destroy
	    end
	    # render json: response.data.to_json
	    respond_to do |format|
	      	format.js { @div_id = params[:id] }
	    end
	end

	def destroy_show
	    respond_to do |format|
	      	format.html
	      	format.js { @file = @response.data }
	    end
  	end

	def copy
		# Creates a copy of the specified file.
		copied_file = @drive.files.copy.request_schema.new({ 'title' => params[:title] })

		response = $client.execute(
		    :api_method => @drive.files.copy,
		    :body_object => copied_file,
		    :parameters => { 'fileId' => params[:id] })

		# render json: response.data.to_json
		redirect_to root_path
	end

	def copy_show
	    respond_to do |format|
	      	format.html
	      	format.js { @file = @response.data }
	    end
  	end

  	def share
  		respond_to do |format|
	      	format.html
	      	format.js { @file_id = params[:id] }
	    end
  	end

  	def share_files
  		##used for share from landing fileClick choose team, and search inside teamPage and share file
  		if params[:teams].present?
	        teams = params[:teams].split(',')
	        teams.each do |team|
	        		#teamFile array for share_team_files method flexbility
	        		teamfile = [TeamFile.create(circle_id: team, file_id: params[:file_id])]
	        		
	        		circle = Circle.find(team)
				  	team_members = circle.team_members

				    if team_members.present?
			    		team_members.each do |team_member|
			    		user = User.find_by(google_id: team_member.google_id)
			    		  Circle.share_team_files($client, user, teamfile)
				    	end
					end
	        end
	    end
	    if params[:search_files_box].present?

	    	teams = [params[:circle_id]]
	        teams.each do |team|
	        		params[:file_id] = params[:search_files_box]
	        		#teamFile array for share_team_files method flexbility
	        		teamfile = [TeamFile.create(circle_id: team, file_id: params[:file_id])]
	        		
	        		circle = Circle.find(team)
				  	team_members = circle.team_members

				    if team_members.present?
			    		team_members.each do |team_member|
			    		user = User.find_by(google_id: team_member.google_id)
			    		  Circle.share_team_files($client, user, teamfile)
				    	end
					end
	        end
  		end
	    #to add success counter on permission share
	   	respond_to do |format|
	      	format.html 
	      	format.js { @file_id = params[:file_id] }
	    end
  	end

	def touch
		# Set the file's updated time to the current server time. Update a file's modified date.
		response = $client.execute(:api_method => @drive.files.touch,
    							:parameters => { 'fileId' => params[:id] })

	    render json: response.data.to_json
	end

	def trash
		# Moves a file to the trash.
		response = $client.execute(:api_method => @drive.files.trash,
    							:parameters => { 'fileId' => params[:id] })

	    render json: response.data.to_json
	end

	def untrash
		# Restores a file from the trash.
		response = $client.execute(:api_method => @drive.files.untrash,
    							:parameters => { 'fileId' => params[:id] })
	    render json: response.data.to_json
	end

	def search_files
		response = $client.execute(:api_method => @drive.files.list, :parameters => {"q" => "title contains '#{params[:q]}'" })
		files = []
		response.data.items.each do |file|
			files.push({ id: file.id, name: file.title}) unless file.labels.trashed
		end
		render json: files.to_json
	end

	private

	def discover_api
		# Authorizing the client and constructing a Google+ service.
		@drive = $client.discovered_api('drive', 'v2')
	end

	def get_file
    	# Get the file from drive
	    @response = $client.execute(:api_method => @drive.files.get,
    								:parameters => { 'fileId' => params[:id] })
	end
end

app/helpers/files_helper.rb
module FilesHelper
end

app/views/files/_file_copy.html.erb
<h3 class="pink-header">Create a Copy</h3>
<%= form_tag(copy_file_path(file.id), :id => "copy_file", :method => "post") do %>
  <div class="form-group">
    Title: <%= text_field_tag "title", "", class: "white-pink", placeholder: "Enter the title for the copy" %>
  </div>
  <p><button class="btn" id="copy_button">OK</button></p>
<% end %>

app/views/files/_file_delete.html.erb
<div id="delete-file-response-body">
  <h3 class="pink-header">Are you sure?</h3>
  <%= form_tag(file_path(file.id), :id => "delete_file", :method => "delete", remote: true) do %>
    <%= submit_tag "Yes", class: "btn" %>
  <% end %>
</div>

app/views/files/_new_doc_insert.html.erb
<p>Success, file added:<p>

<p><%= file['title'] %><p>
<p><a href="<%= file['alternateLink'] %>" target="_blank">View File</a><p>

app/views/files/_new_insert.html.erb
<p>Success, file added:<p>

<p><%= file['title'] %><p>
<p><a href="<%= file['alternateLink'] %>" target="_blank">View File</a><p>

app/views/files/_team_share.html.erb
<div id="js-team-share-result-body">
  <h3 class="pink-header">Share with Team</h3>
  <%= form_tag(share_files_files_path, :id => "share_team_document_form", class: "contactForm", :method => "post", remote: true) do %>
    <%= hidden_field_tag "file_id", file_id %>
    <div class="form-group">
      <p><label for="query">Search your teams:</label>
        <%= text_field_tag "teams", "", class: "white-pink", id: "search_team", placeholder: "Search Team" %></p>
    </div>
    <p><%= submit_tag "Share", class: "btn" %></p>
  <% end %>
  <p style="color: #e10707; font-size:10px;">This does not create a copy of the file.  To do this use TeamFile.new from inside the team page, or copy this one and share it.</p>
</div>

<script type="text/javascript">
  jQuery(document).ready(function () {
    $("#search_team").tokenInput("/circles/circles_names.json", {
      theme: "facebook",
      crossDomain: false,
      hintText: "Type to search teams"
    });
    $(".token-input-dropdown-facebook").css("z-index","9999")
  });
</script>
<style>
  #token-input-search_team {
    width: auto;
  }
</style>

app/views/files/copy_show.js.erb
$('.files-display-modal').modal('hide');

$("#empty-modal-body-container").empty();
$("#empty-modal-body-container").html("<%= escape_javascript(render partial: 'file_copy', locals: { file: @file }) %>");
$("#modal-window-empty").modal("show");

$('#copy_button').click(function(){
	$('#copy_file').submit();
});

app/views/files/destroy.js.erb
$("#delete-file-response-body").empty()
$("#delete-file-response-body").html('<p>' + 'Successfully deleted file Boss' + '</p>');
var id = '#' + '<%= @div_id %>'
$(id).hide();

app/views/files/destroy_show.js.erb
$('.files-display-modal').modal('hide');

$("#empty-modal-body-container").empty();
$("#empty-modal-body-container").html("<%= escape_javascript(render partial: 'file_delete', locals: { file: @file }) %>");
$("#modal-window-empty").modal("show");

app/views/files/insert_new.js.erb
<% if @file.mimeType == 'application/vnd.google-apps.document' %>
	$("#new-doc-modal-body").html("<%= escape_javascript(render partial: 'new_insert', locals: { file: @file }) %>");
	$("#new-doc-modal-footer").show();
<% else %>
	$("#new-ss-modal-body").html("<%= escape_javascript(render partial: 'new_insert', locals: { file: @file }) %>");
	$("#new-ss-modal-footer").show();
<% end %>

app/views/files/share.js.erb
$('.files-display-modal').modal('hide');

$("#empty-modal-body-container").empty();
$("#empty-modal-body-container").html("<%= escape_javascript(render partial: 'team_share', locals: { file_id: @file_id }) %>");
$("#modal-window-empty").modal("show");

app/views/files/share_files.js.erb
$("#js-team-share-result-body").empty();

fileID = '<%= @file_id %>'

link = '<a href="https://docs.google.com/file/d/'+fileID+'/edit?usp=drivesdk" target="_blank">View</a>'

html = '<p>' + 'Success shared with your teams.' + '</p>' + 
	   '<p>' + link + '</p>'

$("#js-team-share-result-body").html(html);