config/routes.rb
GooglePlay::Application.routes.draw do
  resources :signin, :only => [:index] do
    collection do
      post :connect
      post :disconnect
      post :save_user
      get :refresh_connection
    end
  end

  resources :activities, :only => [:index, :show] do
    resources :comments, :only => [:index]
    collection do
      get :search
    end
  end

  resources :comments, :only => [:show]

  resources :calendars, :only => [:show, :create, :update, :destroy] do
    resources :calendar_events, :only => [:index, :new, :show, :create, :update, :destroy], :path => 'events', :as => 'events' do
      member do
        post :move
        get :destroy_show, path: 'destroy'
      end
      collection do
        post :quick_add
      end
    end
    member do
      post :clear
    end
  end

  resources :calendar_lists, :only => [:index, :show, :create, :update, :destroy]

  resources :circles do
    member do
      get :destroy_show, path: 'destroy'
      get :circle_files
      post :add_message
      post :add_wallpin
      delete :delete_item
      get :circle_peoples
      post :remove_team_member
    end
    collection do
      get :circles_names
      post :add_friend_to_team
    end
  end

  resources :colors, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :calendar, :as => 'calendar'
      get :event, :as => 'event'
    end
  end

  resources :files, :only => [:index, :show, :create, :update, :destroy] do
    resources :file_comments, :only => [:index, :show, :create, :update, :destroy], :path => 'comments', :as => 'comments' do
      resources :replies, :only => [:index, :show, :create, :update, :destroy]
      collection do
        get :comments_show, :path => "show", :as => "show"
      end
    end
    member do
      post :copy
      post :touch
      post :trash
      post :untrash
      get :destroy_show, path: 'destroy'
      get :copy_show, path: 'copy'
      get :share
    end
    collection do
      post :insert_new
      post :share_files
     
      get :search_files
    end
  end

  resources :peoples, :only => [:index, :show] do
    collection do
      get :search
      get :monea_email_search
      get :list_by_activity
      post :add_people
    end
  end

  resources :task_lists, :only => [:index, :show, :create, :update, :destroy] do
    resources :tasks, :only => [:index, :show, :new, :create, :update, :destroy] do
      member do
        put :complete_task
        get :destroy_show, path: 'destroy'
        get :complete_show, path: 'complete'
      end
      collection do
        post :clear
      end
    end
    member do
      get :destroy_show, path: 'destroy'
    end
    collection do
      post :create_task
    end
  end

  root 'signin#index'
end

app/controllers/signin_controller.rb
class SigninController < ApplicationController

  skip_before_filter :verify_token, except: [:disconnect]

  def index
    # Create a string for verification
    if !session[:state]
      state = (0...13).map{('a'..'z').to_a[rand(26)]}.join
      session[:state] = state
    end
    @state = session[:state]
  end

  def connect
    
    if !session[:token]
      if session[:state] == params[:state]
        responseData = request.body.read

        $authorization.code = responseData.split(',')[0]
        $client.authorization = $authorization
        id_token = responseData.split(',')[1]
        encoded_json_body = id_token.split('.')[1]
        
        encoded_json_body += (['='] * (encoded_json_body.length % 4)).join('')
        json_body = Base64.decode64(encoded_json_body)
        body = JSON.parse(json_body)
        gplus_id = body['sub']
        email = body['email']
        session[:token] = responseData.split(',')[2]
        session[:user_google_id] = gplus_id
        session[:user_email] = email
      else
        render json: 'The client state does not match the server state.'.to_json
      end
    end
    
    $client.authorization.access_token = session[:token]
    @plus = $client.discovered_api('plus', 'v1')

    response = $client.execute(@plus.people.get,
                              {'userId'=> 'me'}).data

    result = JSON.parse(response.to_json)
    
    if result.has_key?('error')
      reset_session
      render json: "Error in User Credentials; error result returned in api request".to_json
    else
      @user = User.find_by(google_id: session[:user_google_id])
      if !@user
        User.join_and_create(session[:user_email], session[:user_google_id])
        render json: result.to_json
      else
        render json: result.to_json
      end
    end
   
  end

  def refresh_connection
      reset_session
      redirect_to root_path
  end

  def disconnect
    # Using either the refresh or access token to revoke if present.
    token = session[:token]
    $client.authorization.access_token = nil
    
    reset_session
    # Sending the revocation request and returning the result.
    revokePath = 'https://accounts.google.com/o/oauth2/revoke?token=' + token
    uri = URI.parse(revokePath)
    request = Net::HTTP.new(uri.host, uri.port)
    request.use_ssl = true
    request.get(uri.request_uri).code

    render json: 'User disconnected.'.to_json
  end

  # def save_user
  #   # Save or find User
  #   @user =  User.find_by(google_id: params[:id])
  #   if @user
  #     session[:user_email] = @user.email
  #     render json: 'User is already saved and email set in session persistUser Endpoint.'.to_json
  #   else
  #     user = User.new(google_id: params[:id], email: params[:email])
  #     if user.save
  #       drive = $client.discovered_api('drive', 'v2')
  #       team_members = TeamMember.all.where(google_id: user.google_id)
  #       if team_members.present?
  #         team_members.each do |team_member|
  #           teamfiles = team_member.circle.team_files
  #           if teamfiles
  #             teamfiles.each do |teamfile|
  #               new_permission = drive.permissions.insert.request_schema.new({
  #                 'value' => user.email,
  #                 'type' => "user",
  #                 'role' => "reader"
  #               })

  #               result = $client.execute(:api_method => drive.permissions.insert,
  #                           :body_object => new_permission,
  #                           :parameters => { 'fileId' => teamfile.file_id })
  #             end
  #           end
  #         end
  #       end
  #       render json: 'newUser is saved persistUser Endpoint..'.to_json
  #     else
  #       render json: 'newUser is not saved EERRROOOORRRR persistUser Endpoint..'.to_json
  #     end
  #   end
  #   session[:user_google_id] = params[:id]
  # end


private



end

app/views/signin/_landingActionButtons.html.erb
 <!-- Profile actionBoard left box -->
<div id="profile" class="about-div image" style="background-image: url(/assets/infinity_3.jpg);">
    <!-- profile appended here -->
</div>
<!-- actionBoard right box -->
<div class="about-div employees">
      <div class="w-clearfix employees-container">
        <div class="about-employee">
            <div class="table-cell-wrapper">
                <a class="user-button-landing action-button" href="https://mail.google.com/mail/u/0/?view=cm&ui=2&tf=0&fs=1" target="_blank"> 
                   <img class="contact-icon" src="<%= asset_path('mailB icon.png') %>" alt="asset-error">
                  Email.new 
                </a>
            </div>
        </div>
        <div class="about-employee">
           <div class="employee-bio text-buffer">
                <p class="bio-text">Edit your monea settings</p>
                <br>
                <a class="btn no-text-decoration" href="javascript:void(0)">.monea</a>
            </div>
            <div class="table-cell-wrapper">
              <p class="user-button-landing">Profile.edit </p>
            </div>
        </div>
        <div class="about-employee">
            <div class="table-cell-wrapper">
              <a class="user-button-landing action-button" id="view-teams" href="javascript:void(0)"> 
                 <img class="contact-icon" src="<%= asset_path('teams icon.png') %>" alt="asset-error">
                Teams (all) </a>
            </div>
        </div>
        <div class="about-employee">
            <div id="new-to-do-button-container" class="employee-bio text-buffer">
                <p class="bio-text">Create a new toDo task</p>
            </div>
            <div class="table-cell-wrapper">
              <p class="user-button-landing"> toDo.new </p>
            </div>
        </div>
        <div class="about-employee">
            <div class="table-cell-wrapper">
              <a class="user-button-landing action-button" data-toggle="modal" data-target="#modal-window" data-remote=true href="/peoples"> 
                 <img class="contact-icon" src="<%= asset_path('user icon.png') %>" alt="asset-error">
                Networks (people) </a>
            </div>
        </div>
        <div class="about-employee">
            <div class="employee-bio text-buffer">
                <p class="bio-text">Create a new moneaTeam</p>
                <br>
                <a id="team_new" class="btn no-text-decoration" href="javascript:void(0)">.new</a>
            </div>
            <div class="table-cell-wrapper">
              <p class="user-button-landing"> Team.new </p>
            </div>
        </div>

      </div>

</div>

app/views/signin/_modals.html.erb
<div class="modal fade" id="modal-window-signin-error" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-small-width">
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="pink-header">Authentication Error</h3>
			</div>
			<div id="signin-in-error-modal-body" class="modal-body">
			</div>
			<div id="" class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
			</div>
		</div>
	</div>
</div>
		
<div class="modal fade" id="modal-window-quick-create-event" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-medium-width">
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="pink-header">Quickly Add Event</h3>
				<p>Same principles as google quick add.</p>
			</div>
			<div id="quick-events-modal-body" class="modal-body">
				<%= form_tag("/calendars/primary/events/quick_add", :method => "post", remote: true) do %>
					<div class="form-group">
						Text: <%= text_field_tag "event[text]", "", class: "white-pink", placeholder: "e.g 10am deliver report", id: "text" %>
						<%= hidden_field_tag "event[circle_id]", params[:id] %>
					</div>
				  <%= submit_tag "Add", class: "btn" %>
				<% end %>
			</div>
			<div id="quick_create_event_footer" class="modal-footer" style="display:none;">
				<p><button id="quick_create_button_close" class="btn close" data-dismiss="modal" aria-hidden="true">Close</button></p>
			</div>
		</div>
	</div>
</div>

<!-- for searching People in header box -->
<div class="modal fade" id="modal-window-g-plus-search-result" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-search-width">
		<div class="modal-content">
		    <div class="modal-header">
		      	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		      	<h3 id="myModalLabel" style="text-align: center;">Search G+ People Result</h3>
		    </div>
		    <div class="modal-body">
		    	 <div class="search_result"></div>
		    	 <button class="btn btn-primary pull-right" id="next_button_gplus_people_search">Next</button>
		    </div>
		    <div class="hide">
	    		<%= form_tag(search_peoples_path, :id => "googlePlus_search_form", :method => "get") do %>
	    			<%= hidden_field_tag "query", "" %>
	    			<%= hidden_field_tag "next_page_token", "" %>
	    		<% end %>
		   	</div>

		    <div class="modal-footer">
		      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
		    </div>
	  	</div>
	</div>
</div>

<div class="modal fade" id="modal-window-create-circle" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-medium-width">
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="pink-header">Create a new Team</h3>
				<p>You will become the owner.  Add people and colleagues after creation.</p>
			</div>
			<div class="modal-body">
				<%= form_tag(circles_path, :id => "create_circle_form", :method => "post") do %>
					<div class="form-group">
						Name: <%= text_field_tag "circle[display_name]", "", class: "white-pink", placeholder: "Enter Name", id: "name" %>
						Description: <%= text_area_tag "circle[description]", "", class: "white-pink", placeholder: "Description", id: "description" %>
						<%= hidden_field_tag "circle[user_id]", "" %>
					</div>
				<% end %>
			</div>
			<div class="modal-footer">
				<button class="btn" id="create_button_circle">Create</button>
			</div>
		</div>
	</div>
</div>

<!-- import document or SS user choice modal -->
<div class="modal fade" id="modal-window-new-file-import" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-medium-width">
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="pink-header">Document or Spreadsheet?</h3>
			</div>
			<div class="modal-body">
				<p>
					<a id="create_spreadsheet" class="w-inline-block action-button" href="#">
          				<img class="grid-button" src="<%= asset_path('newss icon.png') %>" alt="5490da4fafc8621f3f4641f3_grid%20button.svg">
        			</a>
        			<a id="create_document" class="w-inline-block action-button" href="#">
          				<img class="grid-button" src="<%= asset_path('newdoc icon.png') %>" alt="5490da4fafc8621f3f4641f3_grid%20button.svg">
        			</a>
        		</p>
			</div>
			<div class="modal-footer">
				<p>This will import the file into your cloud drive.</p>
			</div>
		</div>
	</div>
</div>

<!-- modal that sets SS mimeType after import user choice -->
<div class="modal fade" id="modal-window-create-spreadsheet" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-medium-width">
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="pink-header">Import Spreadsheet</h3>
			</div>
			<div class="modal-body">
				<br>
				<%= form_tag(files_path, :id => "create_spreadsheet_form", :method => "post", :multipart => true) do %>
					<div class="form-group">
						Select Spreadsheet: <%= file_field_tag "file", class: "form-control", :accept => ".csv, .xlsx, .xls" %>
						<%#= hidden_field_tag "circle_id", params[:id] %>
					</div>
				<% end %>
				<br>
			</div>
			<div class="modal-footer">
				<button class="btn" id="create_button_spreadsheet">Create</button>
				<p>Press ESC to exit</p>
			</div>
		</div>
	</div>
</div>

<!-- modal that sets DOC mimeType after import user choice -->
<div class="modal fade" id="modal-window-create-document" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-medium-width">
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="pink-header">Import Document</h3>
			</div>
			<div class="modal-body">
				<br>
				<%= form_tag(files_path, :id => "create_document_form", :method => "post", :multipart => true) do %>
					<div class="form-group">
						Select Document: <%= file_field_tag "file", class: "form-control" %>
						<%#= hidden_field_tag "circle_id", params[:id] %>
					</div>
				<% end %>
				<br>
			</div>
			<div class="modal-footer">
				<p><button class="btn" id="create_button_document">Create</button></p>
				<p>Press ESC to exit</p>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="modal-window-create-tasklist" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-medium-width">
	  	<div class="modal-content">
	    	<div class="modal-header">
	      		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	      		<h3 id="myModalLabel">Create Task List</h3>
	    	</div>
	    	<div class="modal-body">
	      		<%= form_tag(task_lists_path, :id => "create_tasklist_form", :method => "post") do %>
	        		<div class="form-group">
	          			Title: <%= text_field_tag "task_list[title]", "", class: "form-control", placeholder: "Title" %>
	        		</div>
	      		<% end %>
	    	</div>
	    	<div class="modal-footer">
	      		<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	      		<button class="btn btn-primary" id="create_button_tasklist">Create</button>
	    	</div>
	  	</div>
	</div>
</div>

app/views/signin/_unAuth_landing.html.erb
  <!-- sliderWrapper --> 
  <div id="not-auth-ops" class="w-slider slider-homepage" data-animation="fade" data-duration="700" data-infinite="1" data-delay="4000" data-autoplay="1">

    <div class="w-slider-mask">
      <!-- slide one  -->
      <div class="w-slide slide-1 escape-parete">
          <!-- nav Menu -->
          <nav class="w-nav-menu nav-menu">
              <%= render 'layouts/navButtonsUnAuth' %>
          </nav>  <!-- end of nav -->
          <!-- slider arrows container -->
          <div class="full-screen-arrows-container">
            <div class="slider-left-arrow right">
              <img class="slider-arrow" src="<%= asset_path('right arrow.svg') %>" alt="no-asset-error">
            </div>
            <div class="slider-left-arrow">
              <img class="slider-arrow left" src="<%= asset_path('right arrow.svg') %>" alt="no-asset-error">
            </div>
          </div>
          <!-- slider center text -->
          <a class="w-inline-block slide-text-container" href="#">
            <h1 class="project-title">
              <div id="gConnect">
                  <button class="g-signin"
                      data-scope="<%= ENV['PLUS_LOGIN_SCOPE'] %>"
                      data-requestvisibleactions="http://schemas.google.com/AddActivity"
                      data-clientId="<%= ENV['CLIENT_ID'] %>"
                      data-state=""
                      data-accesstype="offline"
                      data-callback="onSignInCallback"
                      data-theme="dark"
                      data-cookiepolicy="single_host_origin">
                  </button>
              </div>
            </h1>
            <h2 class="homepage-h2">A web platform built for business, and for the future </h2>
          </a>
      </div> <!-- end of slide one -->

      <!-- slide two unAuth landing -->
      <div class="w-slide slide-1 escape-sospensione">
          <div class="full-screen-arrows-container">
            <div class="slider-left-arrow right">
              <img class="slider-arrow" src="<%= asset_path('right arrow.svg') %>" alt="no-asset-error">
            </div>
            <div class="slider-left-arrow">
              <img class="slider-arrow left" src="<%= asset_path('right arrow.svg') %>" alt="no-asset-error">
            </div>
          </div>
          <a class="w-inline-block slide-text-container" href="#">
            <h1 class="project-title">Tools</h1>
            <h2 class="homepage-h2">a web IT infrastructure to help run your business</h2>
          </a>
          <nav class="w-nav-menu nav-menu" role="navigation">
              <%= render 'layouts/navButtonsUnAuth' %>
          </nav>  <!-- end of nav -->
      </div>

    </div> <!-- end of slider mask -->

    <!-- arrows for slider inside main slider wrapper only -->
    <div class="w-slider-arrow-left slider-left-arrow"></div>
    <div class="w-slider-arrow-right slider-left-arrow right"></div>
    <div class="w-slider-nav w-round slide-nav"></div>
</div> <!-- end of slider wrapper non-auth ops -->

app/views/signin/index.html.erb
  <!-- pink landing loading wrapper -->
  <div class="loader-wrapper" data-ix="display-none">
    <div class="loader-content"><img class="logo-loader" src="<%= asset_path('loader.gif') %>" width="80" alt="549c43b5e136e6e56c054a1e_loader.gif">
      <div class="loader-text"><span class="loader-text-low-opacity">Loading...<br xmlns="http://www.w3.org/1999/xhtml"></span>Welcome to work.</div>
    </div>
  </div>

  <%= render 'layouts/moneaActionBar' %>
  <%= render 'unAuth_landing' %>
  <%= render 'layouts/mobileNav' %>

<!-- authorised ops -->
<div class="w-clearfix content">
      <!-- start of authNav -->
      <nav class="w-nav-menu nav-menu" role="navigation">
          <%= render 'layouts/navButtons' %>
      </nav>  <!-- end of nav -->
    
    <!-- auth main landing image -->
    <div class="about-hero-container">
      <h1 class="about-hero-title">monea.Build News</h1>
      <div id="news-flash-container" class="news-splash">
          
      </div>
    </div>

    <!-- profile box and actionBoard LANDING/SIGIN partial -->
    <%= render 'landingActionButtons' %>

     <!-- foodNews left box -->
     <div data-ix="show-on-scroll" class="about-div">
      <p class="about">
        <a class="w-inline-block all-projects-button" href="#">
          <img class="grid-button" src="<%= asset_path('food icon.png') %>" alt="asset error">
        </a>
        Click to see stories from BBC, reuters and other news feeds.
      </p>
    </div>
    <!-- foodNews right box -->
    <div data-ix="show-on-scroll" class="about-div image">
    </div>

    <!-- START OF CALENDAR -->

    <!-- diary left box -->
     <div id="calendar-anchor" data-ix="show-on-scroll" class="about-div slider">
      <div class="w-slider slider-about" data-animation="slide" data-duration="500" data-infinite="1">
        <div id="diary-container" class="w-slider-mask">
          <!-- append calendar events here -->
        </div>
        <div class="w-slider-arrow-left slider-left-arrow"><img class="slider-arrow left" src="<%= asset_path('slider arrow right black.png') %>" alt="asset-error">
        </div>
        <div class="w-slider-arrow-right slider-left-arrow right"><img class="slider-arrow" src="<%= asset_path('slider arrow right black.png') %>" alt="asset error">
        </div>
        <div class="w-slider-nav w-round slider-about-nav"></div>
      </div>
    </div>
    <!-- diary right box -->
    <div data-ix="show-on-scroll" class="about-div title">
      <h1 class="h1-about">
        <a class="w-inline-block action-button" href="#">
          <img id="quick_add_event" class="grid-button" src="<%= asset_path('qaddevent.png') %>" alt="asset-error">
        </a>
        <a class="w-inline-block action-button" href="#">
          <img id="add_event" class="grid-button" src="<%= asset_path('calendar icon.png') %>" alt="5490da4fafc8621f3f4641f3_grid%20button.svg">
        </a>
        <br>
        yourDiary
      </h1>
    </div>

    <!-- START OF TASKS -->
    <!-- pending tasks left box -->
    <div id="tasks-anchor" class="about-div title">
      <h1 class="h1-about">
        <a class="add-to-do" href="javascript:void(0)"><img class="contact-icon action-button" src="<%= asset_path('ntask icon.png') %>" alt="asset-error">
        </a>
        Pending Tasks
      </h1>
    </div>
    <!-- pending tasks right box -->
    <div data-ix="show-on-scroll" class="about-div slider">
      <div class="w-slider slider-about" data-animation="slide" data-duration="500" data-infinite="1">
        <div id="tasks-pending-container" class="w-slider-mask">
          <!-- append tasks here -->
        </div>
        <div class="w-slider-arrow-left slider-left-arrow"><img class="slider-arrow left" src="<%= asset_path('slider arrow right black.png') %>" alt="asset-error">
        </div>
        <div class="w-slider-arrow-right slider-left-arrow right"><img class="slider-arrow" src="<%= asset_path('slider arrow right black.png') %>" alt="asset error">
        </div>
        <div class="w-slider-nav w-round slider-about-nav"></div>
      </div>
    </div>
    <!-- completed tasks left box -->
    <div data-ix="show-on-scroll" class="about-div slider">
      <div class="w-slider slider-about" data-animation="slide" data-duration="500" data-infinite="1">
        <div id="tasks-complete-container" class="w-slider-mask">
          <!-- append tasks here -->
        </div>
        <div class="w-slider-arrow-left slider-left-arrow"><img class="slider-arrow left" src="<%= asset_path('slider arrow right black.png') %>" alt="asset-error">
        </div>
        <div class="w-slider-arrow-right slider-left-arrow right"><img class="slider-arrow" src="<%= asset_path('slider arrow right black.png') %>" alt="asset error">
        </div>
        <div class="w-slider-nav w-round slider-about-nav"></div>
      </div>
    </div>
    <!-- completed tasks right box -->
    <div data-ix="show-on-scroll" class="about-div title">
      <h1 class="h1-about">
        <a class="add-to-do" href="javascript:void(0)"><img class="contact-icon action-button" src="<%= asset_path('ntask icon.png') %>" alt="asset-error">
        </a>
        completed Tasks
      </h1>
    </div>
    
    <!-- START of FILES -->
    <!-- user files left box -->
    <div id="files-anchor" class="about-div title">
      <h1 class="h1-about">
        <a class="w-inline-block action-button new_doc" href="#">
          <img class="grid-button" src="<%= asset_path('newdoc icon.png') %>" alt="5490da4fafc8621f3f4641f3_grid%20button.svg">
        </a>
        <a class="w-inline-block action-button new_file_import" href="#">
          <img class="grid-button" src="<%= asset_path('import icon.png') %>" alt="5490da4fafc8621f3f4641f3_grid%20button.svg">
        </a>
        <a class="w-inline-block action-button new_ss" href="#">
          <img class="grid-button" src="<%= asset_path('newss icon.png') %>" alt="5490da4fafc8621f3f4641f3_grid%20button.svg">
        </a>
        <br>
        yourFiles
      </h1>
    </div>
    <!-- user files right box -->
    <div class="about-div employees">
      <div id="latest-files-container" class="w-clearfix employees-container">
        <!-- files appended here -->
      </div>
    </div>
    <!-- shared files left box -->
    <div class="about-div employees">
      <div id="shared-files-container" class="w-clearfix employees-container">
        <!-- files appended here -->
      </div>
    </div>
    <!-- shared files right box -->
    <div class="about-div title">
      <h1 class="h1-about">
        <a class="w-inline-block action-button new_doc" href="#">
          <img class="grid-button" src="<%= asset_path('newdoc icon.png') %>" alt="5490da4fafc8621f3f4641f3_grid%20button.svg">
        </a>
        <a class="w-inline-block action-button new_file_import" href="#">
          <img class="grid-button" src="<%= asset_path('import icon.png') %>" alt="5490da4fafc8621f3f4641f3_grid%20button.svg">
        </a>
        <a class="w-inline-block action-button new_ss" href="#">
          <img class="grid-button" src="<%= asset_path('newss icon.png') %>" alt="5490da4fafc8621f3f4641f3_grid%20button.svg">
        </a>
        <br>
        sharedFiles
      </h1>
    </div>
     <!-- EEEEEENNNNNNDDDDDDDDD OOOFFFF LLAAANNNNDDDINNG -->
 </div> <!--  end of clearFix authContent container -->
 <br>
 <br>
 <footer class="footer">
      <div class="w-clearfix footer-content">
        <div class="footer-text">monea.build 2015&nbsp;</div>
        <a class="w-inline-block logo-small" href="/"><img src="<%= asset_path('contemplate white.svg') %>" width="80" alt="asset-error">
        </a>
        <div class="footer-text">All rights reserved</div>
      </div>
 </footer> 
 <div id="state" class="hide"><%= @state %></div>

 <%= render 'modals' %>