config/routes.rb
GooglePlay::Application.routes.draw do
  resources :signin, :only => [:index] do
    collection do
      post :connect
      post :disconnect
      post :save_user
      get :refresh_connection
    end
  end

  resources :activities, :only => [:index, :show] do
    resources :comments, :only => [:index]
    collection do
      get :search
    end
  end

  resources :comments, :only => [:show]

  resources :calendars, :only => [:show, :create, :update, :destroy] do
    resources :calendar_events, :only => [:index, :new, :show, :create, :update, :destroy], :path => 'events', :as => 'events' do
      member do
        post :move
        get :destroy_show, path: 'destroy'
      end
      collection do
        post :quick_add
      end
    end
    member do
      post :clear
    end
  end

  resources :calendar_lists, :only => [:index, :show, :create, :update, :destroy]

  resources :circles do
    member do
      get :destroy_show, path: 'destroy'
      get :circle_files
      post :add_message
      post :add_wallpin
      delete :delete_item
      get :circle_peoples
      post :remove_team_member
    end
    collection do
      get :circles_names
      post :add_friend_to_team
    end
  end

  resources :colors, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get :calendar, :as => 'calendar'
      get :event, :as => 'event'
    end
  end

  resources :files, :only => [:index, :show, :create, :update, :destroy] do
    resources :file_comments, :only => [:index, :show, :create, :update, :destroy], :path => 'comments', :as => 'comments' do
      resources :replies, :only => [:index, :show, :create, :update, :destroy]
      collection do
        get :comments_show, :path => "show", :as => "show"
      end
    end
    member do
      post :copy
      post :touch
      post :trash
      post :untrash
      get :destroy_show, path: 'destroy'
      get :copy_show, path: 'copy'
      get :share
    end
    collection do
      post :insert_new
      post :share_files
     
      get :search_files
    end
  end

  resources :peoples, :only => [:index, :show] do
    collection do
      get :search
      get :monea_email_search
      get :list_by_activity
      post :add_people
    end
  end

  resources :task_lists, :only => [:index, :show, :create, :update, :destroy] do
    resources :tasks, :only => [:index, :show, :new, :create, :update, :destroy] do
      member do
        put :complete_task
        get :destroy_show, path: 'destroy'
        get :complete_show, path: 'complete'
      end
      collection do
        post :clear
      end
    end
    member do
      get :destroy_show, path: 'destroy'
    end
    collection do
      post :create_task
    end
  end

  root 'signin#index'
end

app/models/circle.rb
class Circle < ActiveRecord::Base
	
	belongs_to :user
	has_many :team_members, dependent: :destroy
	has_many :team_files, dependent: :destroy
	has_many :messages, dependent: :destroy
	has_many :wallpins, dependent: :destroy

	def self.share_team_files client, user, teamfiles
		drive = client.discovered_api('drive', 'v2')
		google = GoogleService.new(client, drive)
		team_name = Circle.find(teamfiles.first.circle_id).display_name
		teamfiles.each do |teamfile|
          	#files_shared = true
          	google.insert_new_files_permission( user, teamfile.file_id )
        end
	end
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController

	before_action :get_circle, except: [:index, :create, :circles_names, :add_friend_to_team]
	before_filter :authorize_user, only: :show

	def index
		@circles = User.find_by(google_id: params[:user_google_id]).circles
    	respond_to do |format|
		  	format.html
		  	format.json { render json: @circles }
		end
	end
	#retrieve users circle names
	def circles_names
		gSession_id = session[:user_google_id]
		user = User.find_by(google_id: gSession_id)
	    if user.present?
	    	circle_names = user.load_my_team_names(params[:q], gSession_id)
		end
	    render json: circle_names.to_json
  	end
  	# retrieves a circles teamFiles
  	def circle_files
  		@team_files = @circle.team_files
		render json: @team_files
  	end
    ##retrieves for landing, AJAX fetch
  	def circle_peoples
  		@team_members = @circle.team_members
		render json: @team_members
  	end
    # post request for adding G+ friends to a moneateam
  	def add_friend_to_team
  		team = Circle.find(params[:circle_id])
		person_g_id = params[:person_google_id]
		user = User.find_by(google_id: person_g_id)
		teamfiles = team.team_files
		team_member = TeamMember.find_by(circle_id: team.id, google_id: person_g_id) 
		#files_shared = false
		if team_member.present?
			team_member
		else
			team_member = TeamMember.create(circle_id: team.id, google_id: person_g_id)
            if teamfiles.present?
            	Circle.share_team_files($client, user, teamfiles)
            end
        end
	    respond_to do |format|
	      	format.js { @team_member = team_member }
	    end
  	end

  	def remove_team_member
  		@member = TeamMember.find_by(circle_id: params[:id], google_id: params[:google_id])
		if @member.destroy 
			@message = "Success".to_json
			render json: @message
		else
			@message = "Failure".to_json
			render json: @message
		end
  	end

	def new
		@circle = Circle.new
	end

	def show
		# Create a string for verification
	    if !session[:state]
	      state = (0...13).map{('a'..'z').to_a[rand(26)]}.join
	      session[:state] = state
	    end
	    @state = session[:state]
	    @messages = @circle.messages.all
	    @wallpins = @circle.wallpins.all
	    #@user = session[:user_email]
		respond_to do |format|
			format.html
	    	format.js { @circle }
    	end
	end

	def edit
		respond_to do |format|
	    	format.js { @circle }
    	end
	end

	def create
		case
		when !params[:circle][:user_id]
			redirect_to root_path, notice: 'Cannot find user, trying signing in and out'
		when params[:circle][:user_id]
			circle = Circle.new(circle_params)
			circle.user_id = User.find_by(google_id: params[:circle][:user_id]).id
			if circle.save
				redirect_to circle_path(circle.id)
			else
				redirect_to root_path , notice: 'Something went wrong trying to add circle boss' 
			end
		end 
	end

	def update
		if @circle.update_attributes(circle_params)
			# render json: @circle
			redirect_to circle_path(@circle.id)
		else
			# render json: "Circle not updated"
			redirect_to root_path
		end
	end

	def destroy
		if @circle.destroy
			# render json: "Circle deleted"
			redirect_to root_path
		else
			# render json: "Circle not deleted"
			redirect_to root_path
		end
	end

	def destroy_show
		respond_to do |format|
	    	format.js { @circle }
    	end
	end

	def add_message
		@message = @circle.messages.new(text: params[:circle][:message], added_by: session[:user_email])
		if @message.save
			respond_to do |format|
	    		format.js { @message }
    		end
    	else
    		respond_to do |format|
	    		format.js { @message = nil }
    		end
    	end
	end

	def add_wallpin
		@pin = @circle.wallpins.new(summary: params[:circle][:summary], added_by: session[:user_email], file_link: params[:circle][:file_link] )
		if @pin.save
			respond_to do |format|
	    		format.js { @pin }
    		end
    	else
    		respond_to do |format|
	    		format.js { @pin = nil }
    		end
    	end
	end

	def delete_item 
		case 
		when params[:circle][:item_type] == "pin" 
			@item = @circle.wallpins.find_by(id: params[:circle][:item_id])
			@type = "pin"
		when params[:circle][:item_type] == "message" 
			@item = @circle.messages.find_by(id: params[:circle][:item_id])
			@type = "message"
		when params[:circle][:item_type] == "team-file" 
			@item = @circle.team_files.find_by(file_id: params[:circle][:item_id])
			@type = "team-file"
		end
		@div_id = @type + '-' + @item.id.to_s
		if params[:circle][:item_type] == "team-file"
			@div_id = params[:circle][:item_id]
		end
		if @item.destroy
			respond_to do |format|
	    		format.js { @div_id }
    		end
    	else
    		respond_to do |format|
	    		format.js { @item = nil }
    		end
    	end
	end

	private

	def authorize_user
		if !session[:user_google_id]
			redirect_to root_path
		else
			if @circle.user_id == current_user.id
				return true
			else
				if @circle.team_members.where(google_id: session[:user_google_id]).present?
					return true
				else
					redirect_to root_path
				end
			end
		end
	end

	def get_circle
		@circle = Circle.find(params[:id])
	end

	def circle_params
   		params.require(:circle).permit(:display_name, :description)
 	end
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/views/circles/_circle_delete.html.erb
 <h3 class="pink-header">Are you sure?</h3>
  <%= form_tag(circle_path(circle.id), :id => "delete_circle", :method => "delete") do %>
  <% end %>
  <button class="btn" id="delete_button">OK</button>
  <script type="text/javascript">
    $('#delete_button').click(function(){
      $('#delete_circle').submit();
    });
  </script>

app/views/circles/_circle_edit.html.erb
      <h3 class="pink-header">Circle Details</h3>
      <%= form_tag(circle_path(circle.id), :id => "update_circle", class: "contactForm", :method => "put") do %>
        <div class="form-group">
          <label for="name">Name:</label>
          <div class="controls">
            <%= text_field_tag "circle[display_name]", circle.display_name, class: "white-pink", placeholder: "Name", id: "name" %>
          </div>
        </div>
        <div class="form-group">
          <label for="description">Description:</label>
          <div class="controls">
            <%= text_area_tag "circle[description]", circle.description, class: "white-pink", placeholder: "Description", id: "description", rows: "10" %>
          </div>
        </div>
      <% end %>
    </div>
    <button class="btn" id="update_button">Update</button>
    <script type="text/javascript">
      $('#update_button').click(function(){
        $('#update_circle').submit();
      });
    </script>

app/views/circles/_circle_modals.html.erb
<!-- modal for append non-displayed files -->
<div class="modal fade" id="modal-window-view-teamfiles" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">
				<h3 class="pink-header">your TeamFiles</h3>
				<div id="landing-teamfiles-append"></div>
			</div>
			<div class="modal-footer">
				<p>Press ESC to exit</p>
			</div>
		</div>
	</div>
</div>

<!-- modal for teams append on teamSignin -->
<div class="modal fade" id="modal-window-view-teams" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="pink-header">yourTeams</h3>
			</div>
			<div class="modal-body">
				<div class="" id="landing-teams-append"></div>
			</div>
			<div class="modal-footer">
				<p>Press ESC to exit</p>
			</div>
		</div>
	</div>
</div>

<!-- add team message modal -->
<div class="modal fade" id="modal-window-circle-add-message" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-search-width">
		<div class="modal-content">
		    <div class="modal-header">
		      	<h3 class="pink-header">Add message</h3>
		    </div>
		    <div id="modal-body-circle-add-message" class="modal-body">
		    	<%= form_tag(add_message_circle_path, :method => "post", remote: true) do %>
					<div class="form-group">
						Message: <%= text_area_tag "circle[message]", "", class: "white-pink", placeholder: "Enter some text as a message", id: "message_text" %>
						<br>
						<%= submit_tag "Post",  class: "btn" %>
					</div>
				<% end %>
		    </div>
		    <div class="modal-footer">
		      <p>Press ESC to exit</p>
		    </div>
	  	</div>
	</div>
</div>

<!-- add team wallPin -->
<div class="modal fade" id="modal-window-circle-add-wallpin" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-search-width">
		<div class="modal-content">
		    <div class="modal-header">
		      	<h3 class="pink-header">Add WallPin</h3>
		    </div>
		    <div id="modal-body-circle-add-wallpin" class="modal-body">
		    	<%= form_tag(add_wallpin_circle_path, :method => "post", remote: true) do %>
					<div class="form-group">
						Message: <%= text_area_tag "circle[summary]", "", class: "white-pink", placeholder: "Enter some text as a message", id: "wallpin_summary" %>
						<br>
						File Link: <%= text_field_tag "circle[file_link]", "", class: "white-pink", placeholder: "Enter a link", id: "wallpin_file_link" %>
						<br>
						<%= submit_tag "Pin",  class: "btn" %>
					</div>
				<% end %>
		    </div>
		    <div class="modal-footer">
		      <p>Press ESC to exit</p>
		    </div>
	  	</div>
	</div>
</div>

<!-- file search user gDrive modal here, and in modals partial on landing -->
<div class="modal fade" id="modal-window-quick-search-files" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="pink-header">Search your Drive</h3>
				<p style="font-size:10px;">This searches your drive and does not create a copy when sharing.  Use File.import otherwise.</p>
			</div>
			<div id="js-team-share-result-body" class="modal-body">
				<div class="form-group">
				      <%= form_tag(share_files_files_path, class: "contactForm", :method => "post", remote: true) do %>
					        <%= hidden_field_tag "file_id", "" %>
					        <%= hidden_field_tag "circle_id", params[:id] %>
					        <div class="form-group">
					          <div class="controls">
					            Text: <%= text_field_tag "search_files_box", class: "form-control requiredField" %>
					          </div>
					        </div>
					        <%= submit_tag "Share", class: "btn btn-main-o" %>
				      <% end %>
				</div>
			</div>
			<div id="" class="modal-footer">
				<p>Press ESC to exit</p>
			</div>
		</div>
	</div>
</div>

<!-- search form new.ppl inside team page, email search -->
<div class="modal fade" id="modal-window-add-circle-member" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-medium-width">
		<div class="modal-content">
		    <div class="modal-header">
		      	<h3 class="pink-header">Search monea Users</h3>
		      	<p style="font-size:10px;">You can add colleagues from your friends list from your main work page.</p>
		    </div>
		    <div class="modal-body">
		      	<%= form_tag(search_peoples_path, :id => "add_circle_member_form", class: "contactForm", :method => "get") do %>
		      		
		        	<div class="form-group">
		          		<label for="query">Search:</label>
		          		<div class="controls">
		          			<%= text_field_tag "query", "", class: "white-pink", placeholder: "Search user by email" %>
		          			<%= hidden_field_tag "circle_id", params[:id] %>
		          		</div>
		        	</div>
		      	<% end %>
		    </div>
		    <div class="modal-footer">
		      <button class="btn" id="create_button_circle_member">Search</button>
		      <p>Press ESC to exit</p>
		    </div>
	  	</div>
	</div>
</div>

<!-- email result modal for appending results into see Circles.js line 279 -->
<div class="modal fade" id="modal-window-circle-members-result" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-search-width">
		<div class="modal-content">
		    <div class="modal-header">
		      	<h3 class="pink-header" style="text-align: center;">Search Email Result</h3>
		    </div>
		    <div class="modal-body" id="monea-email-search-js-return-body">
		    	<%= form_tag(add_people_peoples_path, :id => "add_circle_member_search_form", :method => "post", remote: true) do %>
		    		<%= hidden_field_tag "circle_id", params[:id] %>
		    		<div id="search_result"></div>
		    		<br>
					<%= submit_tag "Add",  class: "btn" %>
		    	<% end %>
		    </div>
		    <div class="modal-footer">
		      <p>Press ESC to exit</p>
		    </div>
	  	</div>
	</div>
</div>

<!-- for searching People in header box -->
<div class="modal fade" id="modal-window-g-plus-search-result" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-search-width">
		<div class="modal-content">
		    <div class="modal-header">
		    
		      	<h3 id="myModalLabel" style="text-align: center;">Search G+ People Result</h3>
		    </div>
		    <div class="modal-body">
		    	 <div class="search_result"></div>
		    	 <button class="btn btn-primary pull-right" id="next_button_gplus_people_search">Next</button>
		    </div>
		    <div class="hide">
	    		<%= form_tag(search_peoples_path, :id => "googlePlus_search_form", :method => "get") do %>
	    			<%= hidden_field_tag "query", "" %>
	    			<%= hidden_field_tag "next_page_token", "" %>
	    		<% end %>
		   	</div>

		    <div class="modal-footer">
		      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
		    </div>
	  	</div>
	</div>
</div>

<!-- delete pin or message modal -->
<div class="modal fade" id="modal-window-destroy-item" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-small-width">
		<div class="modal-content">
		    <div id="js-item-delete-result-body" class="modal-body">
		        <h3 class="pink-header">Are you sure?</h3>
		        <%= form_tag(delete_item_circle_path, :method => "delete", remote: true) do %>
		        <br>
		        <%= hidden_field_tag "circle[item_type]", "" %>
		        <%= hidden_field_tag "circle[item_id]", "" %>
		        <%= submit_tag "Yes", class: 'btn' %>
		        <% end %>
		    </div>
		    <div class="modal-footer">
		      <p>Press ESC to exit</p>
		    </div>
	  	</div>
	</div>
</div>

<div class="modal fade" id="modal-window-create-circle-document" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-medium-width">
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="pink-header">Import a TeamFile</h3>
				<p style="font-size:10px;">This upload creates and inserts a new copy into the cloud.  Use File.share from this page or team.share from your main work page, if your file is already in the cloud.  </p>
			</div>
			<div class="modal-body">
				<%= form_tag(files_path, :id => "create_circle_document_form", class: "contactForm", :method => "post", :multipart => true) do %>
					<%= hidden_field_tag "circle_id", params[:id] %>
					<div class="form-group">
						<label for="file">Select Document:</label>
						<div class="controls">
							<%= file_field_tag "file", class: "form-control requiredField" %>
						</div>
					</div>
				<% end %>
				<br><br>
			</div>
			<div class="modal-footer">
				<button class="btn btn-primary" id="create_button_circle_document">Create</button>
				<p>Press ESC to exit</p>
			</div>
		</div>
	</div>
</div>

app/views/circles/_circle_show.html.erb
<div class="modal-dialog modal-medium-width">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">Circle Details</h3>
    </div>
    <div class="modal-body">
      <div class="form-group">
        Name: <%= text_field_tag "circle[display_name]", circle.display_name, class: "form-control", placeholder: "Name", id: "name", readonly: "readonly" %>
        Description: <%= text_area_tag "circle[description]", circle.description, class: "form-control", placeholder: "Description", id: "description", readonly: "readonly" %>
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
  </div>
</div>

app/views/circles/add_friend_to_team.js.erb
$('#add-to-team-form').empty()
team_name = '<%= Circle.find(@team_member.circle_id).display_name %>';
circle_id = '<%= @team_member.circle_id %>'
// team_name = 'hello';
// circle_id = 'hello'
$('#add-to-team-form').append(

		'<p>' + 'Success, your friend has been added to the team, to go to the moneaTeam Page click the below link' + '</p>' +
		'<p>' + '<a href="/circles/'+circle_id+' " target="_blank">' + team_name + '</a>' + '</p>'

);

app/views/circles/add_message.js.erb
$("#modal-body-circle-add-message").html("Success, message added.");

message = {
	text: '<%= @message.text %>',
	id: '<%= @message.id %>',
	added_by: '<%= @message.added_by %>'
}

$("#team-messages-container").prepend(uiHelper.teamMessagesHtml(message));

 Webflow.require("slider").redraw();

 

app/views/circles/delete_item.js.erb
$("#js-item-delete-result-body").html("Success, item deleted.");

var id = '#' + '<%= @div_id %>';
$(id).hide();

app/views/circles/show.html.erb
<!-- pink landing loading wrapper for TEAM -->
<div class="loader-wrapper" data-ix="display-none">
	<div class="loader-content"><img class="logo-loader" src="<%= asset_path('loader.gif') %>" width="80" alt="549c43b5e136e6e56c054a1e_loader.gif">
	  <div class="loader-text"><span class="loader-text-low-opacity">Loading...<br xmlns="http://www.w3.org/1999/xhtml"></span>your Team Page</div>
	</div>
</div>

<%= render 'layouts/moneaActionBar' %>
<%= render 'layouts/mobileNav' %>
 <!-- authorised ops -->
<div class="w-clearfix content">
    <!-- start of authNav -->
    <nav class="w-nav-menu nav-menu" role="navigation">
      <%= render 'layouts/navButtons' %>
    </nav>  <!-- end of nav -->
    <!-- auth main landing image -->
    <div class="about-hero-container">
      <h1 class="about-hero-title"><%= @circle.display_name %> teamPage</h1>
      <div id="news-flash-container" class="news-splash">
      	<a style="margin-left:65%;">Owner: <%= User.find(@circle.user_id).email %></a>
      	<a data-remote="true" href="<%= destroy_show_circle_path(@circle.id) %>"><img class="contact-icon action-button" style="display: inline-block;" src="<%= asset_path('trash-white.png') %>" alt="asset-error"></a>
		    <a data-remote="true" href="<%= edit_circle_path(@circle.id) %>"><img class="contact-icon action-button" style="display: inline-block;" src="<%= asset_path('edit icon.png') %>" alt="asset-error"></a>
      </div>
    </div>
    <!-- profile box and actionBoard LANDING/SIGIN partial -->
    <%= render 'landingTeamActionButtons' %>

    <!-- START OF MESSAGES AND PINS -->
    <!-- pending messages left box -->
    <div data-ix="show-on-scroll" class="about-div title">
      <h1 class="h1-about">
        <a id="create_team_message" class="add-to-do" href="javascript:void(0)"><img class="contact-icon action-button" src="<%= asset_path('mailB icon.png') %>" alt="asset-error">
        </a>
        team Messages
      </h1>
    </div>

    <% icon_names = ['passion.svg', 'communication.svg', 'diligence.svg', 'innovation.svg', 'reliability.svg' ] %>
    <!-- messages display slider right box -->
    <div data-ix="show-on-scroll" class="about-div slider">
      <div class="w-slider slider-about" data-animation="slide" data-duration="500" data-infinite="1">
        <div id="team-messages-container" class="w-slider-mask">
        	<% @messages.each do |m| %>
        		<% index = rand(0..4) %>
                <div id="message-<%= m.id %>" class="w-slide slide-about">
                    <div class="about-slide-container">
                    	<img class="about-icon" src="<%= asset_path(icon_names[index]) %>" alt="asset-error">
                       	<h3><%= m.text %></h3>
                       	<h3><%= m.added_by %></h3>
                   		<h3><a href="javascript:void(0)" data-id="<%= m.id %>" data-item="message" class="destroy-item"><img class="contact-icon action-button" style="display: inline-block;" src="<%= asset_path('trash-white.png')%>" alt="asset-error"></a><h3>
                    </div><!-- about-slide-container -->
                </div><!-- w-slide slide-about -->
            <% end %>
        </div>
        <div class="w-slider-arrow-left slider-left-arrow"><img class="slider-arrow left" src="<%= asset_path('slider arrow right black.png') %>" alt="asset-error">
        </div>
        <div class="w-slider-arrow-right slider-left-arrow right"><img class="slider-arrow" src="<%= asset_path('slider arrow right black.png') %>" alt="asset error">
        </div>
        <div class="w-slider-nav w-round slider-about-nav"></div>
      </div>
    </div>
    <!-- completed tasks left box -->
    <div data-ix="show-on-scroll" class="about-div slider">
      <div class="w-slider slider-about" data-animation="slide" data-duration="500" data-infinite="1">
        <div id="team-pins-container" class="w-slider-mask">
          <% @wallpins.each do |wp| %>
        		<% index = rand(0..4) %>
                <div id="pin-<%= wp.id %>" class="w-slide slide-about" style="background-color:#62DF71;">
                    <div class="about-slide-container">
                    	<img class="about-icon" src="<%= asset_path(icon_names[index]) %>" alt="asset-error">
                       	<h3><%= wp.summary %></h3>
                       	<% if wp.file_link %>
	                       	<h3><a href="<%= wp.file_link %>" target="_blank">LinkToFile</a></h3>
                       	<% end %>
                       	<h3 style="font-size:15px;"><%= wp.added_by %></h3>
                   		<h3><a href="#" class="destroy-item" data-id="<%= wp.id %>" data-item="pin"><img class="contact-icon action-button" style="display: inline-block;" src="<%= asset_path('trash-white.png')%>" alt="asset-error"></a><h3>
                    </div><!-- about-slide-container -->
                </div><!-- w-slide slide-about -->
            <% end %>
        </div>
        <div class="w-slider-arrow-left slider-left-arrow"><img class="slider-arrow left" src="<%= asset_path('slider arrow right black.png') %>" alt="asset-error">
        </div>
        <div class="w-slider-arrow-right slider-left-arrow right"><img class="slider-arrow" src="<%= asset_path('slider arrow right black.png') %>" alt="asset error">
        </div>
        <div class="w-slider-nav w-round slider-about-nav"></div>
      </div>
    </div>
    <!-- completed tasks right box -->
    <div data-ix="show-on-scroll" class="about-div title">
      <h1 class="h1-about">
      	<a id="create-team-wallpin" href="javascript:void(0)"><img class="contact-icon action-button" src="<%= asset_path('ntask icon.png') %>" alt="asset-error">
        </a>
        team Pins
      </h1>
    </div>
    <!-- START of TEAM FILES -->
    <!-- team files left box -->
   

    <div data-ix="show-on-scroll" id="files-anchor" class="about-div title">
      <h1 class="h1-about">
        <a class="w-inline-block action-button new_doc" href="#">
          <img class="grid-button" src="<%= asset_path('newdoc icon.png') %>" alt="5490da4fafc8621f3f4641f3_grid%20button.svg">
        </a>
        <a class="w-inline-block action-button create-team-file" href="#">
          <img class="grid-button" src="<%= asset_path('import icon.png') %>" alt="5490da4fafc8621f3f4641f3_grid%20button.svg">
        </a>
        <a class="w-inline-block action-button new_ss" href="#">
          <img class="grid-button" src="<%= asset_path('newss icon.png') %>" alt="5490da4fafc8621f3f4641f3_grid%20button.svg">
        </a>
        <br>
        team Files
      </h1>
    </div>
    <!-- team files right box -->
    <div data-ix="show-on-scroll" class="about-div employees">
      <div id="team-latest-files-container" class="w-clearfix employees-container">
        <!-- files appended here -->
      </div>
    </div>

    <!-- START of TEAM MEMBERS -->
    <!-- team members left box -->
    <div class="about-div employees">
      <div id="team-members-container" class="w-clearfix employees-container">
        <!-- files appended here -->
      </div>
    </div>
    <!-- team files right box -->
    <div id="" class="about-div title">
      <h1 class="h1-about">
        
        <a class="w-inline-block action-button add-team-member" href="#">
          <img class="grid-button" src="<%= asset_path('t-add icon.png') %>" alt="5490da4fafc8621f3f4641f3_grid%20button.svg">
        </a>
        <br>
        team Members
      </h1>
    </div>
    

</div> <!-- end of CLEARFIX CONTENT DIV PART ONE -->

<!-- TEAM MODALS FOR USER ACTIONS -->
<%= render 'circle_modals' %>

<!-- NOTDISPLAYED -->
<div id="circle_id" class="hide"><%= params[:id] %></div>
<div id="gConnect" class="hide">
      <button class="g-signin"
          data-scope="<%= ENV['PLUS_LOGIN_SCOPE'] %>"
          data-requestvisibleactions="http://schemas.google.com/AddActivity"
          data-clientId="<%= ENV['CLIENT_ID'] %>"
          data-state=""
          data-accesstype="offline"
          data-callback="onSignInCallback"
          data-theme="dark"
          data-cookiepolicy="single_host_origin">
      </button>
</div>
<div id="team-owner" data-value="<%= @circle.user_id == @current_user.id %>"></div>